import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import AppHeader from '@/components/app/header/AppHeader'
import FilterMenu from '@/components/app/header/FilterMenu'
import Wrapper from '@/components/app/Wrapper'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, 'min-h-screen flex flex-col relative')}>
        <AppHeader />
        {children}
      </body>
    </html>
  )
}
