import { Toaster } from 'sonner'
import Providers from '@/lib/providers'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, 'min-h-screen flex flex-col relative')}>
        <Providers>
          {children}
          <Toaster
            richColors
            closeButton
          />
        </Providers>
      </body>
    </html>
  )
}
